Update contribution_tools.md
carbon-language/carbon-lang pull request #1517
Opened 2022-07-21 15:14 UTC by PariKhaleghi

VS Code is a Code editor, not an IDE!

2022-07-22 17:45 UTC, jonmeow requested changes
Can you please explain the distinction? VS Code supports code editing, building, and debugging: what's missing that you don't consider it an IDE?

2022-07-22 17:56 UTC, PariKhaleghi commented
> Can you please explain the distinction? VS Code supports code editing, building, and debugging: what's missing that you don't consider it an IDE?

As you know, VS Code doesn't do anything by itself. All these tasks that you mentioned are done by plugins. Basically, we call an IDE an environment that does these things in addition to several other services, specially and by default for a language / framework (single tool belt), and all those things are published exclusively by the IDE publishing company (expert support is guaranteed).

2022-07-22 22:05 UTC, jonmeow approved these changes
I'm not sure I think there's the same distinction, but per https://code.visualstudio.com/docs/supporting/faq#_what-is-the-difference-between-visual-studio-code-and-visual-studio-ide it seems VS Code is trying to brand itself a code editor so approving.

2022-07-22 22:14 UTC, jonmeow commented on docs/project/contribution_tools.md
>  Carbon development. Some settings changes must be made separately:
```suggestion
[Visual Studio Code](https://code.visualstudio.com/) is a code editor used by
several of us. We provide [recommended extensions](/.vscode/extensions.json) to
assist Carbon development. Some settings changes must be made separately:
```

Note the pre-commit failure, this is just formatting.

2022-07-23 15:39 UTC, jonmeow approved these changes

2022-07-23 15:47 UTC, merged