Add tests to for range NoSpace
carbon-language/carbon-lang pull request #1619
Opened 2022-07-23 16:32 UTC by Garz4

Add tests to `for_range` that covers different positions of `:`.

2022-07-23 17:11 UTC, pacion requested changes
What about changing the name of the variables? Before1, Before2.. doesn't fit well imo.

2022-07-23 17:13 UTC, Garz4 commented
Yeah, what do you think about renaming them to `BeforeLeftColon`, `BeforeRightColon` and `BeforeJointColon`? I'm trying to debug why is it failing right now though.

2022-07-23 17:47 UTC, Garz4 commented
I see the problem, when performing replacement of
```cpp
for (int i: items) {
```
the expected result is
```cpp
for (int i in items) {
```
but the actual result has an extra space between `in` and `items`, as follows:
```cpp
for (int i in  items) {
```

2022-07-24 01:13 UTC, jonmeow commented
Note tests are failing.

That said, this tool is pretty exploratory right now. asoffer is proposing a redesign in https://github.com/carbon-language/carbon-lang/issues/1534, which seems fairly likely. It may make sense to limit time spent here right now.

2022-07-26 01:23 UTC, Garz4 commented
I agree with #1534, so I will close this for now.

2022-07-26 01:23 UTC, closed without merging