Fixed grammar and spelling issues
carbon-language/carbon-lang pull request #1632
Opened 2022-07-24 08:09 UTC by danielathome19

Removed most grammatical issues for clarity and ease of readability.

2022-07-24 17:38 UTC, jonmeow requested changes
Thank you for the suggestions. I've noted spots where I think that either it's better to keep the original phrasing (which we should prefer by default, in order to minimize churn), or where I think a more significant change may be necessary. I think there are also some spots where the way we're phrasing things may not match what you're expecting. Anyways, all noted in comments.

2022-07-24 17:38 UTC, jonmeow commented on docs/project/goals.md
> +Community members should understand how and why decisions are made and have the
```suggestion
Community members should understand how and why decisions are made, and have the
```

As above

2022-07-24 17:38 UTC, jonmeow commented on docs/project/goals.md
> +set expectations for people joining and to help remind and anchor us on
```suggestion
set expectations for people joining, and to help remind and anchor us on
```

I view the comma here as stylistic: there's two `and`s in this sentence so having the comma here can help clarify the intended reading. There might be some better rephrasing, but it's probably better to keep the comma for now.

2022-07-24 17:38 UTC, jonmeow commented on docs/project/goals.md
> +**Developer tooling.** We need developers to be productive in reading and writing
```suggestion
**Developer tooling.** We need developers to be productive while reading and writing
```

I'm fine adding a word here, but probably `while` is more suitable.

2022-07-24 17:38 UTC, jonmeow commented on docs/project/goals.md
> +knowledge of the environment in which it will run. This need not be precise but
```suggestion
knowledge of the environment in which it will run. This need not be precise, but 
```

I think this one is correct.

2022-07-24 17:38 UTC, jonmeow commented on docs/project/goals.md
> +Carbon forward at a reasonable pace and at a reasonable cost. Simultaneously,
```suggestion
Carbon forward at a reasonable pace and with a reasonable cost. Simultaneously,
```

These seem fairly even word choices to me, let's keep the old form unless there's a specific reason for changing.

2022-07-24 17:38 UTC, jonmeow commented on docs/project/goals.md
> +an evolving language must not leave software behind to languish but bring
```suggestion
an evolving language must not leave software behind to languish, instead bringing
```

Comma is definitely correct here. Suggesting a slight phrasing change to emphasize contrast.

2022-07-24 17:38 UTC, jonmeow commented on docs/project/goals.md
> +enabling appropriate and effective usage of features and creating incentives
```suggestion
enabling appropriate and effective usage of features, and creating incentives
```

Per other comments -- let's leave commas when there are multiple `and`s in the sentence.

2022-07-24 17:38 UTC, jonmeow commented on docs/project/goals.md
> +manageable. The simplicity of implementation reduces bugs, and will in most cases
```suggestion
manageable. Simplicity of implementation reduces bugs, and will in most cases
```

I'm not sure that adding `The` is improving this sentence.

2022-07-24 17:38 UTC, jonmeow commented on docs/project/goals.md
> +building systems of large software.
```suggestion
build systems of large software.
```

This is about build systems.

2022-07-24 17:38 UTC, jonmeow commented on docs/project/goals.md
> +platform support. As these platforms evolve, Carbon will have to
```suggestion
platform support. As these platforms evolve over time, Carbon will have to
```

I think there's a certain voice we should retain here.

2022-07-24 17:38 UTC, jonmeow commented on docs/project/goals.md
> +Carbon. If a long and significant study is required to be minimally proficient,
```suggestion
Carbon. If long and significant study is required to be minimally proficient,
```

I think it's correct without `a`.

2022-07-24 17:38 UTC, jonmeow commented on docs/project/goals.md
> +in any way but reflects the fact that they do not provide meaningful value to
```suggestion
in any way, but instead reflects the fact that they do not provide meaningful value to
```

We can increase contrast, but note:
https://www.grammarly.com/blog/comma-before-but/#:~:text=When%20Do%20You%20Need%20a,have%20to%20trip%20you%20up.

2022-07-24 17:38 UTC, jonmeow commented on docs/project/goals.md
> +on ABI and isolate it in source from code that does not need that stability.
```suggestion
on ABI and isolating it in source from code which does not need that stability.
```

relying/isolating matches form. Let's keep the original phrasing.

2022-07-30 23:38 UTC, jonmeow commented
Please note I still have comments you haven't responded to. Also, I've run pre-commit just so that you can see the errors:
https://github.com/carbon-language/carbon-lang/runs/7594798173?check_suite_focus=true

https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md#pre-commit has instructions if you want to run pre-commit locally.

2022-07-31 04:21 UTC, danielathome19 commented
> 

They should all be cleared now -- there were a few hidden comments I missed initially.

2022-07-31 15:34 UTC, jonmeow commented
I don't see any commit that would fix the pre-commit formatting issues, can you please make sure everything's fixed and pushed?

2022-08-03 23:04 UTC, danielathome19 reviewed
Updated

2022-08-09 16:17 UTC, jonmeow commented
Just to note, no commits have been pushed since my last message.

2022-08-12 19:03 UTC, closed without merging