Changed Some Code in C++ File
carbon-language/carbon-lang pull request #1837
Opened 2022-07-30 08:00 UTC by MrKrishnaAgarwal

2022-07-30 08:12 UTC, MrKrishnaAgarwal commented
test / test (macos-latest, opt) (pull_request_target)

**why is this check failing?**

2022-07-30 15:09 UTC, jonmeow requested changes
I'm going to close this PR. I've commented on each proposed change to explain why.

2022-07-30 15:09 UTC, jonmeow commented on common/check_internal.h
> +        "ensure the `|` operator exits the program prior to their "
I don't think this should be changed; `operator|` is the function name in C++.

2022-07-30 15:09 UTC, jonmeow commented on explorer/syntax/lex_scan_helper.cpp
> +auto ReadHashTags(Carbon::StringLexHelper& scan_helper, const int hashtag_num)
We'll sometimes use size_t when it seems appropriate: https://google.github.io/styleguide/cppguide.html#Integer_Types

Perhaps most importantly though, it's size_t in the header and these shouldn't diverge.

2022-07-30 15:09 UTC, jonmeow commented on docs/spec/lang/README.md
> +    TODO: Linkage rules for foreign entities. <br> TODO: Ability to declare
I think it's fine to have multiple TODOs here; we shouldn't use HTML in md files unless absolutely necessary anyways.

2022-07-30 15:09 UTC, closed without merging

2022-07-30 15:10 UTC, jonmeow commented
> test / test (macos-latest, opt) (pull_request_target)
> 
> **why is this check failing?**

For future reference, if you click "details" next to the check, you can read the output from the action.

2022-07-30 15:30 UTC, MrKrishnaAgarwal commented
Okay Thanks 
No Worries 👍

2022-07-30 22:50 UTC, jonmeow commented
@MrKrishnaAgarwal As I'm reviewing more PRs, I see your change to check_internal.h seems to be identical to that in #1699 and lex_scan_helper.cpp is identical to that in #1757. Please make sure you aren't accidentally including changes being made by other developers.

2022-07-31 02:35 UTC, MrKrishnaAgarwal commented
Oh!

I didn't noticed that 
But can I make another PR with the changes of my previous pull request that closed unexpectedly.