add operator to comparsion
carbon-language/carbon-lang pull request #1883
Opened 2022-08-02 15:07 UTC by pmqtt

Implement operator <, <=, > and >=

2022-08-02 16:33 UTC, jonmeow reviewed
Thanks! Generally looks good to me, although I have a few minor comments.

2022-08-02 16:33 UTC, jonmeow commented on explorer/syntax/parser.ypp
> +comparison_operator:
```suggestion
/* TODO: Add NOT_EQUAL */
comparison_operator:
```

Just want to note this since it's kind of the odd operator out now.

2022-08-02 16:33 UTC, jonmeow commented on explorer/syntax/parser.ypp
> +
```suggestion
```

Looks like a stray edit

2022-08-02 16:33 UTC, jonmeow commented on explorer/data/prelude.carbon
> +
```suggestion
```

Just trying to limit blank lines to 1 between, for consistency.

2022-08-02 16:33 UTC, jonmeow commented on explorer/data/prelude.carbon
> +
```suggestion
```
Just trying to limit blank lines to 1 between, for consistency.

2022-08-02 16:33 UTC, jonmeow commented on explorer/data/prelude.carbon
> +
```suggestion
```

Just trying to limit blank lines to 1 between, for consistency.

2022-08-02 16:33 UTC, jonmeow commented on explorer/data/prelude.carbon
> +// ----------------------
I could go either way with these per-operator headers, but probably either Eq and Less should have similar marks, or none of them should.

2022-08-02 16:33 UTC, jonmeow commented on explorer/data/prelude.carbon
> +  // TODO: NotEqual with default impl
These NotEqual comments should only be on the Equal interface (generally true through your edits)

Context: https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/expressions/comparison_operators.md#equality

2022-08-02 17:30 UTC, tkadur commented
Do we want to have separate interfaces for each operation or just have a single `Ord` interface (similar to Rust or Haskell) that all comparison ops desugar into?

2022-08-02 17:55 UTC, jonmeow commented
> Do we want to have separate interfaces for each operation or just have a single `Ord` interface (similar to Rust or Haskell) that all comparison ops desugar into?

Aww, shoot. You made me look again at the design, and I'm realizing how it's significantly different from what's being done here:
https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/expressions/comparison_operators.md#equality

```
choice Ordering {
  Less,
  Equivalent,
  Greater,
  Incomparable
}
interface OrderedWith(U:! Type) {
  fn Compare[me: Self](u: U) -> Ordering;
  default fn Less[me: Self](u: U) -> bool {
    return me.Compare(u) == Ordering.Less;
  }
  default fn LessOrEquivalent[me: Self](u: U) -> bool {
    let c: Ordering = me.Compare(u);
    return c == Ordering.Less or c == Ordering.Equivalent;
  }
  default fn Greater[me: Self](u: U) -> bool {
    return me.Compare(u) == Ordering.Greater;
  }
  default fn GreaterOrEquivalent[me: Self](u: U) -> bool {
    let c: Ordering = me.Compare(u);
    return c == Ordering.Greater or c == Ordering.Equivalent;
  }
}
constraint Ordered {
  extends OrderedWith(Self);
}

// Ordering.Less < Ordering.Equivalent < Ordering.Greater.
// Ordering.Incomparable is incomparable with all three.
external impl Ordering as Ordered;
```

So probably this should be implemented a little closer to that design. I don't think that `default fn` is implemented yet, though, and this design may not be workable without it. But it would still be nice to have comparison. Maybe we can do something like:

```
choice Ordering {
  Less,
  Equivalent,
  Greater,
  Incomparable
}

interface OrderedWith(U:! Type) {
  fn Compare[me: Self](u: U) -> Ordering;
  // TODO: Add `default fn` for Less, LessOrEquivalent, Greater, and GreaterOrEquivalent once it's available.
}
// TODO: constraint Ordered { ... }

impl i32 as OrderedWith(Self) {
  fn Compare[me: Self](other: Self) -> Ordering {
    return __intrinsic_int_compare(me, other);
  }
}

impl String as OrderedWith(Self) {
  fn Compare[me: Self](other: Self) -> Ordering {
    return __intrinsic_str_compare(me, other);
  }
}
```

Note, it may help to do something like having __intrinsic_int_compare return an int, and compare the return value with `==` to convert it into a enum, like:

```
var comp: i32 = __intrinsic_int_compare(me, other);
if (comp == -1) {
  return Ordering.Less;
}
if (comp == 0) {
  return Ordering.Equivalent;
}
if (comp == 1) {
  return Ordering.Greater;
}
return Ordering.Incomparable;
```

Then for now have the simple interfaces:

```
interface LessWith(U:! Type) {
  fn Less[me: Self](other: U) -> Bool;
}

impl i32 as LessWith(Self) {
  fn Less[me: Self](other: Self) -> Bool {
    return me.Compare(other) == Ordering.Less;
  }
}

impl String as LessWith(Self) {
  fn Less[me: Self](other: Self) -> Bool {
    return me.Compare(other) == Ordering.Less;
  }
}
```

Then these kinds of interfaces I think will still match most of the code.

What do you think of this approach?

2022-08-02 18:21 UTC, jonmeow requested changes
See above comment on approach (trying to clean up my dashboard, need a comment here for GH)

2022-08-02 20:26 UTC, pmqtt commented
@jonmeow: I think this approach is nice... I will try to implement that, tomorrow!

2022-08-02 22:13 UTC, jonmeow commented
Just to note here -- here's a link with some working choice returns/matching because the syntax can be a little confusing (I expect it to evolve)

https://carbon.compiler-explorer.com/z/WzWjza7Gx

2022-08-03 22:55 UTC, jonmeow reviewed
Thank you for the changes! Just some more style comments. I really wish we had a formatter for .carbon, I don't want to make much work for you but I think some of the spacing is just accidentally off.

2022-08-03 22:55 UTC, jonmeow commented on explorer/interpreter/interpreter.cpp
> +
```suggestion
```

I think we generally don't have blank lines between cases

2022-08-03 22:55 UTC, jonmeow commented on explorer/interpreter/interpreter.cpp
> +
```suggestion
```

Same as above

2022-08-03 22:55 UTC, jonmeow commented on explorer/interpreter/type_checker.cpp
> +
```suggestion
```

As noted elsewhere, we generally aren't doing blank lines between cases

2022-08-03 22:55 UTC, jonmeow commented on explorer/interpreter/type_checker.cpp
> +
```suggestion
```

As above

2022-08-03 22:55 UTC, jonmeow commented on explorer/testdata/comparison/builtin_comparsion.carbon
> +
```suggestion
```

Odd to have a blank line here

2022-08-03 22:55 UTC, jonmeow commented on explorer/data/prelude.carbon
> +     return false;
Style-wise, I think there are some slight differences between what's written and what I'd expect. To try to illustrate:

```suggestion
    var comp: Ordering = me.(CompareWith(i32).Compare)(other);
    match (comp) {
      case Ordering.Less() => {
        return true;
      }
    }
    return false;
```

Would you prefer to merge as-is and I can just plan a formatting pass separately, or is this something you'd like to clean up? (I wanted to note highlight it though if you're planning on regular contributions, but really this has me back to wondering if we can figure out something fast that could do formatting for us)

2022-08-04 07:01 UTC, pmqtt commented
Of course, I try to clean up behind me, that's a matter of honor. I'm agree with you, we need a formatter for carbon!

2022-08-04 16:55 UTC, jonmeow approved these changes
Thanks for all the changes here! I'm happy to get this support in.

2022-08-04 16:56 UTC, merged