grammar mistakes
carbon-language/carbon-lang pull request #1915
Opened 2022-08-04 12:01 UTC by MrKrishnaAgarwal

2022-08-04 18:13 UTC, jonmeow requested changes

2022-08-04 18:13 UTC, jonmeow commented on docs/design/generics/goals.md
> +-   It makes the behaviour of code more consistent and predictable.
American English spellings are preferred. Please see: https://developers.google.com/style/spelling

2022-08-04 18:15 UTC, jonmeow commented
For a reminder on the style guide, please see:
https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md#google-docs-and-markdown

2022-08-04 18:17 UTC, MrKrishnaAgarwal commented
> For a reminder on the style guide, please see: https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md#google-docs-and-markdown

Sure

2022-08-04 18:17 UTC, MrKrishnaAgarwal commented
Are other changes fine or I can close this pull request

2022-08-04 18:20 UTC, MrKrishnaAgarwal commented
Should I do any other changes you want or is it fine?

2022-08-05 09:24 UTC, MrKrishnaAgarwal commented
@jonmeow 

What happened, please respond 

If other things are fine

2022-08-05 15:31 UTC, jonmeow commented
@MrKrishnaAgarwal I'm going to merge this now, but given your multiple pings over the past day, I want to clearly communicate review priorities in order to hopefully reduce your confusion in the future.

While those of us working on Carbon are fairly active, there are many contributors to Carbon and we're trying to balance all of them. Your contributions, while helpful, also need corrections. If you would take more time to make sure your proposed changes are clean of issues before sending them off, they will get in faster. When we need to correct your edits, you need to expect that we aren't waiting on you to respond, but are instead going to work on other things and come back to your change at some point later.

Does that make sense?

2022-08-05 15:33 UTC, jonmeow approved these changes

2022-08-05 15:33 UTC, merged

2022-08-05 15:38 UTC, MrKrishnaAgarwal commented
Very sorry,
I'll not ping and I'll wait patiently

Sorry for the inconvenience and Thanks