minor mistakes
carbon-language/carbon-lang pull request #1952
Opened 2022-08-08 09:28 UTC by MrKrishnaAgarwal

2022-08-08 12:00 UTC, jonmeow requested changes
Preexisting and preprocessor are both the preferred spelling. Hyphenating is incorrect.

e.g.: https://en.cppreference.com/w/cpp/preprocessor

2022-08-08 12:01 UTC, MrKrishnaAgarwal commented
> Preexisting and preprocessor are both the preferred spelling. Hyphenating is incorrect.
> 
> e.g.: https://en.cppreference.com/w/cpp/preprocessor

Sure
I'll make the changes

2022-08-08 20:40 UTC, jonmeow commented on docs/project/evolution.md
> +easily understand initial summary comment. Authors and leads are encouraged to
"understood" is correct here. As usual, please undo this change.

2022-08-09 15:59 UTC, jonmeow approved these changes

2022-08-09 16:00 UTC, merged

2022-08-09 16:00 UTC, MrKrishnaAgarwal commented
Thanks 👍🏻