Bring in the LLVM CommandLine API
carbon-language/carbon-lang pull request #2156
Opened 2022-09-08 14:00 UTC by micttyl

The change in args of `RunFullCommand` is due to `ParseCommandLineOptions`. Otherwise, `args` should be re-converted back to argv to use the function.

In `RunFullCommand`, `subcommand_args` is almost a stub for RunXSubcommands, because there are two same patterns in two RunXXSubcommands, that should be factored out and taken care possibly before the switch returns.

Use `dummycat` as a workaround for clean up and hide default Categories. I left `Unknown` in the enum, even if LLVM CommandLine handles the case.

2022-09-08 14:20 UTC, micttyl commented
I have no idea how it fails on Ubuntu. Can anyone?

2022-09-08 14:34 UTC, pmqtt commented
> I have no idea how it fails on Ubuntu. Can anyone?

Currently is the build process broken! I have already given a notice on discord!

2022-09-08 18:42 UTC, micttyl commented on toolchain/driver/driver.cpp
> +// Positionals who correspond to subcommands.
I meant, non-positional parameter

2022-09-08 18:56 UTC, micttyl commented
I see @jonmeow @chandlerc in Discord(I am not verified to chat). Please take a look.

2022-09-08 21:18 UTC, chandlerc requested changes
The choice to avoid the LLVM commandline tooling wasn't accidental.

As you're seeing in this PR, the LLVM subsystem isn't a great fit for what we're doing. It also isn't fully flexible, and will make it harder for us to customize the exact behavior of the tool.

Overall, I don't really think using LLVM's commandline APIs provides enough value to be worth the cost.

Is there a problem you're seeing that this fixes? Is there a specific motivation or something you'd like to do that needs this?

2022-09-09 05:10 UTC, micttyl commented
If it was about purely performance, the commandline API may not be the choice. If it was about sitting next to Clang somewhat coherently and looking friendly to existing LLVM developers, we can squash in as many APIs as we can(or we can replace Bazel).

I agree. My code isn't good. It would cost a lot later when we demand some flexibility. In the worst case, we need to send someone to fix the library per se(ouch!). We can quote my PR as how it would be like if we try this API.

No personal motivation. I just need to communicate more with others before putting some work. Let's close it.

2022-09-09 05:10 UTC, closed without merging

2022-09-10 04:20 UTC, chandlerc commented
> If it was about purely performance, the commandline API may not be the choice. If it was about sitting next to Clang somewhat coherently and looking friendly to existing LLVM developers, we can squash in as many APIs as we can(or we can replace Bazel).
> 
> I agree. My code isn't good. It would cost a lot later when we demand some flexibility. In the worst case, we need to send someone to fix the library per se(ouch!). We can quote my PR as how it would be like if we try this API.

FWIW, no problem with your code. =D I think this may just not be the best API for us to use.

> No personal motivation. I just need to communicate more with others before putting some work. Let's close it.

There is a bit of discussion about this on Discord starting here:
https://discord.com/channels/655572317891461132/655578254970716160/1017578524586016880

Not sure if you're able to participate in Discord chat, but it is the place where I find it easiest to bring up ideas and discuss approaches, would be happy to help there. If Discord isn't working for some reason, a) would be interested to understand why, especially if its something we can fix, and b) also happy for you to @-me (and others) into a GitHub Discussion thread as needed for quick questions. =]