Add documentation for operator tokens described in #603. Fixes #1992.
carbon-language/carbon-lang pull request #2519
Opened 2023-01-07 21:12 UTC by Hech

Add documentation to reflect operators currently proposed referencing alternatives considered.

Closes #1992

2023-01-08 08:47 UTC, chandlerc commented
(probably makes sense for Josh to take the first pass at review here as he filed the tracking issue, etc.)

2023-01-18 00:00 UTC, josh11b commented
Sorry, I've had a lot of vacation recently and have not been able to get to this. I have a bit of an accumulated backlog from my vacation and so it will still be a bit before I can look at this PR.

2023-01-24 23:55 UTC, josh11b commented
Please update title to reflect that operator tokens are from #601 and not #603 . I'd remove "Fixes #1992." from the title as well, that info is fine in the first comment.

2023-01-25 16:26 UTC, josh11b requested changes
Please also update the title to say "symbolic tokens" instead of "operator tokens"

2023-01-25 16:26 UTC, josh11b commented on docs/design/lexical_conventions/operator_tokens.md
> +
```suggestion
```

2023-01-25 16:26 UTC, josh11b commented on docs/design/lexical_conventions/operator_tokens.md
> +## Table of contents
This seems to be missing the discussion of sensitivity to the presence or absence of whitespace that is used to disambiguate, see https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p0601.md#whitespace . From a lexing perspective, the important thing is that the presence or absence of whitespace needs to be communicated up the stack. The reason for that is worth explaining here, namely that it is used to distinguish prefix, postfix, and infix forms of the same operator (such as `*`). See [discussion in #syntax](https://discord.com/channels/655572317891461132/709488742942900284/1067600916343165039).

2023-01-25 16:26 UTC, josh11b commented on docs/design/lexical_conventions/operator_tokens.md
> +`a =- b` is read as invalid rather than `a = (-b)`
This doesn't agree with what is written in proposal #601 , see https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p0601.md#background and https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p0601.md#proposal . What you have written here is the "Using the longest sequence of symbols" alternative that we didn't select.

2023-01-25 16:26 UTC, josh11b commented on docs/design/lexical_conventions/operator_tokens.md
> +
There are two more alternatives considered in #601 :

> We could apply different whitespace restrictions or no whitespace restrictions. 

and

> We could require whitespace around a binary operator followed by `[` or `{`.

2023-01-25 16:26 UTC, josh11b commented on docs/design/lexical_conventions/operator_tokens.md
> +The initial tokens interpreted. More to be added as needed.
Could you please clarify this list only covers up to #601 and more have been added since that are not reflected here

2023-01-25 16:26 UTC, josh11b commented on docs/design/lexical_conventions/operator_tokens.md
> +value computation and are used for control flow.
You could mention keyword operators here in the context of operators tokens, but they aren't really relevant in the context of symbolic tokens.

2023-01-25 16:26 UTC, josh11b commented on docs/design/lexical_conventions/operator_tokens.md
> +| `*`   | Indirection or Multiplication |
Indirection, multiplication, and forming pointers

2023-01-25 16:26 UTC, josh11b commented on docs/design/lexical_conventions/operator_tokens.md
> +| `->`  | Return type                   |
`->` is used for return type and also an operator that matches C++ : `p->x` is equivalent to `(*p).x`.

2023-01-25 16:26 UTC, josh11b commented on docs/design/lexical_conventions/operator_tokens.md
> +| `{}`  | Initialization                |
I think `{}` is actually for struct literals, not initialization, but it is also used for the blocks of control flow statements, and the bodies of definitions (classes, functions, and so on).

2023-01-25 16:26 UTC, josh11b commented on docs/design/lexical_conventions/operator_tokens.md
> +| `,`   | Comma                         |
`,` is not an operator, unlike C++. It is used to separate arguments in a function call, elements of a tuple, or parameters of a function declaration.

2023-01-25 16:26 UTC, josh11b commented on docs/design/lexical_conventions/operator_tokens.md
> +| `:`   | Scope                         |
`:` is not for scope, but for binding in patterns.

2023-01-25 16:26 UTC, josh11b commented on docs/design/lexical_conventions/README.md
> +-   an [operator_token](operator_tokens.md)
From a lexing perspective, it is more relevant that these are symbolic (and therefore not under "words") than operators. We want to include tokens that are not operators (like `:`) and exclude tokens that are not symbolic (like `and`).

```suggestion
-   a [symbolic token](symbolic_tokens.md)
```

2023-01-25 16:26 UTC, josh11b commented on docs/design/lexical_conventions/operator_tokens.md
> +<!--
Please rename this file to `symbolic_tokens.md`

2023-01-25 16:26 UTC, josh11b commented on docs/design/lexical_conventions/operator_tokens.md
> +# Operator Tokens
```suggestion
# Symbolic Tokens
```

2023-01-25 16:26 UTC, josh11b commented on docs/design/lexical_conventions/operator_tokens.md
> +overloading like `+`, `*`, `<`, and more.
With the change to symbolic tokens, this needs to be updated. Operators are one use of symbolic tokens, but they are also used in patterns (`:`), declarations (`->` to indicate return type, `,` to separate parameters), statements (`;`, `=`, and so on), and other places (`,` to separate function call arguments).

2023-01-25 16:26 UTC, josh11b commented on docs/design/lexical_conventions/operator_tokens.md
> +| `()`  | Function call                 |
and function declaration

2023-01-26 22:48 UTC, josh11b commented
FYI, I know I put in a lot of suggestions, but don't worry that is completely expected  when first contributing to Carbon.

2023-03-02 00:16 UTC, closed without merging