Update rules_flex to 0.2.1 and rules_bison to 0.2.2
carbon-language/carbon-lang pull request #2877
Opened 2023-06-06 13:52 UTC by PshRealtime

Updates the dependencies flex and bison to latest. Jon Ross-Perkins has stated in the Discord "the patched versions should hopefully go away now that that's in".
New users have issues to build the project, because the former URLs are no longer existent.

2023-06-06 18:35 UTC, PshRealtime commented
I am seeing it myself: XXX_register_toolchains should have also `extra_copts = ["-w"]`.

2023-06-07 03:24 UTC, chandlerc requested changes

2023-06-07 03:24 UTC, chandlerc commented on WORKSPACE
> +m4_register_toolchains(version = "1.4.18", extra_copts = ["-w"])
Looking at the code, it seems to still support omitting the `version` here and picks the default one?

```suggestion
m4_register_toolchains(extra_copts = ["-w"])
```

2023-06-07 03:24 UTC, chandlerc commented on WORKSPACE
> +flex_register_toolchains(version = "2.6.4", extra_copts = ["-w"])
Same as above, let's continue to pick up the default:

```suggestion
flex_register_toolchains(extra_copts = ["-w"])
```

2023-06-07 03:24 UTC, chandlerc commented on WORKSPACE
> +bison_register_toolchains(version = "3.3.2", extra_copts = ["-w"])
```suggestion
bison_register_toolchains(extra_copts = ["-w"])
```

2023-06-07 16:16 UTC, jonmeow approved these changes
Thank you for the update! (leaving this in case chandlerc has more comments)

2023-06-13 05:59 UTC, PshRealtime commented
There is still some issue with pre-commit. I can't reproduce it on my machine. It appears to me out of the concern with the updating of the dependencies. To trace down the issue will need some more effort.
(This pull-request could have also been stalled, because I didn't push the 'Resolve' button...)

@chandlerc Please provide feedback or merge

2023-06-14 05:02 UTC, chandlerc approved these changes
Nope, looks great!

(And sorry, I forgot that requesting changes blocks someone else from approving, my bad!)

2023-06-14 05:03 UTC, merged