Add vfs support to toolchain.
carbon-language/carbon-lang pull request #2888
Opened 2023-06-09 19:31 UTC by jonmeow

This adds vfs support to the toolchain, allowing Driver to take in-memory inputs in tests. As a consequence, I'm simplifying SourceBuffer: rather than allowing tests to pass in their own memory buffer, I'm using InMemoryFileSystem to push for greater consistency with production code. This does hit a quirk where I need to be careful about null terminator handling because fuzzer imports don't always have one, but that's probably more robust anyways.

2023-06-11 19:04 UTC, zygoloid requested changes

2023-06-11 19:04 UTC, zygoloid commented on toolchain/driver/driver_fuzzer.cpp
> +  auto fs = llvm::vfs::getRealFileSystem();
What do you think about creating an `InMemoryFileSystem` here? It seems a bit concerning to allow the fuzzer to read from arbitrary files on the file system. I mean, it's not likely to find `/dev/zero` or similar and run forever, but it certainly could. Eventually, filling that `InMemoryFileSystem` with a known set of example files would be nice too, but just getting to the point where the fuzzer isn't also fuzzing the file system itself would be a nice advantage of switching to a vfs :)

(Also, once the driver starts being able to write to files, we definitely don't want it to be able to overwrite arbitrary real files when fuzzing.)

I'm totally happy for you to say "not in this PR".

2023-06-11 19:04 UTC, zygoloid commented on toolchain/driver/driver_test.cpp
> +static constexpr llvm::StringLiteral TestFileName = "test_file.txt";
```suggestion
static constexpr llvm::StringLiteral TestFileName = "test_file.carbon";
```

2023-06-11 19:04 UTC, zygoloid commented on toolchain/parser/parse_tree_fuzzer.cpp
> +  llvm::errs() << "made\n";
```suggestion
```

2023-06-11 19:04 UTC, zygoloid commented on toolchain/source/source_buffer.cpp
> +    return Error(llvm::formatv("`{0}` is over the 2MB input limit.", filename));
```suggestion
    return Error(llvm::formatv("`{0}` is over the 2GB input limit.", filename));
```
or maybe
```suggestion
    return Error(llvm::formatv("`{0}` is over the 2GiB input limit.", filename));
```

2023-06-12 18:43 UTC, jonmeow commented on toolchain/driver/driver_fuzzer.cpp
> +  auto fs = llvm::vfs::getRealFileSystem();
Done

2023-06-12 20:19 UTC, zygoloid approved these changes

2023-06-12 20:19 UTC, merged