Update main.cpp
carbon-language/carbon-lang pull request #2894
Opened 2023-06-10 10:40 UTC by madhupashish

I have made some changes that are Listed below :

1. Added some of the missing include directives.

2. Removed some of unnecessary headers.

3. Added   ' llvm::sys::fs::OpenFlags::OF_Text '   flag when opening the trace file stream to ensure it's opened in text mode.

4. Updated the usage of     'cl::list'    to specify  
    'cl::CommaSeparated'   to  allow comma-separated values.

**Replace this paragraph with a description of what this PR is changing or
adding, and why.**

Closes #ISSUE

2023-06-11 11:57 UTC, madhupashish commented
Please Review it and Merge it.

2023-06-12 16:13 UTC, jonmeow requested changes
All I'm seeing here seems to be removing the formatting we use (we use clang-format via pre-commit, see [here](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md#tools)), with none of the fixes mentioned in the PR comment. Did you push the right change?

2023-06-13 09:23 UTC, madhupashish reviewed
Must Read My New Code

2023-06-13 16:21 UTC, jonmeow reviewed
Thanks! Looking through these changes, I would like to restore a few things.

Can you also check the main PR comment and update it to reflect the changes currently being made? It looks like things have fallen out of sync, e.g. there aren't any include changes.

2023-06-13 16:21 UTC, jonmeow commented on explorer/main.cpp
> +    llvm::errs() << "Execution error: " << result.error() << "\n";
```suggestion
    llvm::errs() << result.error() << "\n";
```

The returned error will already be labeled, so this would be duplicative.

2023-06-13 16:21 UTC, jonmeow commented on explorer/main.cpp
>  }
```suggestion
}

```

We keep blank lines in spots like this per [our style guide](https://google.github.io/styleguide/cppguide.html#Vertical_Whitespace):

> Blank lines immediately inside a declaration of a namespace or block of namespaces may help readability by visually separating the load-bearing content from the (largely non-semantic) organizational wrapper. Especially when the first declaration inside the namespace(s) is preceded by a comment, this becomes a special case of the previous rule, helping the comment to "attach" to the subsequent declaration.

2023-06-13 16:21 UTC, jonmeow commented on explorer/main.cpp
> +                                       cl::init("input.carbon"));
```suggestion
                                       cl::Required);
```

This flag is positional and required. I don't think either value_desc or init have an effect, but if I'm missing something, can you explain with a diff in help output?

2023-06-13 17:42 UTC, madhupashish commented
I have merged all your request and i think now your are also satisfied with my code .
Now you can Merge it.

2023-06-14 18:40 UTC, jonmeow approved these changes
Thank you for the edits. Following up on my previous message, I will rewrite your commit message, but we'd really appreciate if you provide accurate commit messages if you plan to continue contributing.

2023-06-14 18:41 UTC, merged

2023-06-19 15:48 UTC, jonmeow commented
I want to note, we removed this patch because it does not qualify as a Contribution under the terms of Google's contributor license agreement.