[explorer] Add support  for `abstract` virtual methods
carbon-language/carbon-lang pull request #3411
Opened 2023-11-18 15:05 UTC by aneeshdurg

Completing the work from #2761 by adding additional test cases. 
Closes #2512

2023-11-20 20:04 UTC, geoffromer approved these changes

2023-11-20 20:23 UTC, geoffromer requested changes
It looks like the tests aren't passing. I can't tell exactly what the issue is, but running `explorer/autoupdate_testdata.sh` will probably fix it.

2023-11-20 23:22 UTC, zygoloid approved these changes

2023-11-21 01:31 UTC, geoffromer approved these changes

2023-11-21 01:40 UTC, merged